Feat lang
leetcode-pp/leetcode-cheat pull request #33
Opened 2023-10-31 10:07 UTC by rennzhang

新增的国际化配置部分：
![image](https://github.com/leetcode-pp/leetcode-cheat/assets/50518861/c3cdbc2d-c479-432c-a111-da88450f4720)

语言切换功能：
![image](https://github.com/leetcode-pp/leetcode-cheat/assets/50518861/16ba7dad-c1a4-40c2-869f-2762be689366)

2023-10-31 10:15 UTC, rennzhang commented
发现 bug..

2023-10-31 10:27 UTC, rennzhang commented
> 发现 bug..

fixed

2023-10-31 11:49 UTC, azl397985856 requested changes

2023-10-31 11:49 UTC, azl397985856 commented on src/App.js
> +            <TabPane key="changeLang" tab={t("app.setLang")} onClick={changeLang}>
changeLang 放到这里如果是中文还行， 有英文下看不到这个菜单，要滚动到最后才能看到。建议放到这里。

<img width="814" alt="image" src="https://github.com/leetcode-pp/leetcode-cheat/assets/12479470/14d2dae0-9d6f-4944-8a72-4ad911ece5a7">

2023-10-31 11:49 UTC, azl397985856 commented on src/App.js
> +    process.env.NODE_ENV === "development" && initLang();
为什么只有开发环境才 initLang

2023-11-01 03:37 UTC, rennzhang commented on src/App.js
> +    process.env.NODE_ENV === "development" && initLang();
逻辑已调整

2023-11-01 04:46 UTC, azl397985856 approved these changes

2023-11-01 04:47 UTC, merged